[package]
name = "stavka"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.44.1", features = ["full"] }
tokio-uring = { version = "0.5.0", features = ["bytes"] }
xxhash-rust = { version = "0.8.15", features = ["xxh3"] }
